services:
  db:
    image: postgres:15
    container_name: nidhara_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nidhara_db
    ports:
      - "5432:5432"
    volumes:
      - nidhara_pgdata:/var/lib/postgresql/data

volumes:
  nidhara_pgdata:
